### ISSUE TITLE
Not a REST API

### ISSUE THREAD

**Issue by ascalabro** [TNChalise/yii2-rest-api-Basic-Application-Template-#1]
The API endpoints are not RESTful at all.
For example, to fetch data on user with ID 1, the http client must call to this url:  
`http://my-yii2-project/api/v2/user/view/?id=1`
For an API to be RESTful, the above call must use the following url instead:
`http://my-yii2-project/api/v2/user/1`

**Comment by TNChalise** [comment]
Thanks for the consideration. Its upto you, how you configure route rules to act. It is just an skeleton project. The main purpose of this project is to give some basic ideas how actually the api is configured. Further more, its open to your opinions.
